# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0035e310a928a5944baff5f2e957026302dc124558bbcbb447cccd9e5df597a5a0d5db0c9f2b48446cd4d4a66bc66b2600570323a80f7ee1053d030b84b3a6f

test:
  secret_key_base: 9139f011da943a89b6714651c75cde85c04e8df536295d0a8dda81a1d582760479d238fdb8bd8783d83e8b4604a844c9ad7659e0c84a727202140d9a02ec4122

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
